version: '3.8'

services:
  database:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: mediawiki_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wiki-internal

  mediawiki:
    image: mediawiki:1.45
    restart: always
    depends_on:
      - database
    ports:
      - "80"
    volumes:
      - mw_images:/var/www/html/images
    networks:
      - wiki-internal
      - dokploy-network

volumes:
  db_data:
  mw_images:

networks:
  wiki-internal:
    driver: bridge
  dokploy-network:
    external: true
